name: test
on: [push]
jobs:
    test:
        runs-on: [ubuntu-latest, windows-latest, macOS-latest]
        steps:
            - uses: actions/checkout@latest
            - uses: julia-actions/setup-julia@latest
              with:
                version: 1.5.0
            - run: julia --project=./ -e "using Pkg; Pkg.instantiate(); Pkg.test()"
